# ============================================================
#  PAI Pulse - Windows autostart installer (counterpart to `manage.sh install`)
#
#  macOS/Linux register Pulse as a launchd/systemd service. Windows has neither,
#  so this script installs a per-user Startup-folder entry that launches Pulse
#  hidden at every login, then starts it now and health-checks :31337.
#
#  Run by the PAI installer's voice step, or standalone:
#     powershell -NoProfile -ExecutionPolicy Bypass -File install-pulse-autostart.ps1
#
#  Exit 0 = Pulse is running and autostart is registered. Non-zero = failure
#  (the caller treats this exactly like a failed `manage.sh install`).
#
#  No admin rights, no Task Scheduler, no mshta - only the per-user Startup
#  folder + wscript, the one windowless path that works on locked-down
#  (Intune-managed) machines.
#
#  ASCII-only on purpose: Windows PowerShell 5.1 reads a UTF-8 file with no BOM
#  as the ANSI codepage, which mangles multibyte characters and can break
#  parsing. Keep this file 7-bit ASCII so it parses everywhere.
# ============================================================

$ErrorActionPreference = 'Stop'

$pulseDir   = $PSScriptRoot
$hiddenPs1  = Join-Path $pulseDir 'start-pulse-hidden.ps1'

if (-not (Test-Path $hiddenPs1)) {
    Write-Error "start-pulse-hidden.ps1 not found at $hiddenPs1 - cannot register autostart."
    exit 1
}

# 1. Write the Startup-folder launcher.
# A .vbs that invokes powershell hidden. Why the .vbs indirection instead of a
# .lnk straight to powershell.exe: bun is a console binary and a Run-key/shortcut
# to powershell can still flash a console for a frame. wscript is a GUI-subsystem
# host, so WshShell.Run(cmd, 0, False) creates the child already-hidden - no flash.
$startup = [Environment]::GetFolderPath('Startup')
$vbsPath = Join-Path $startup 'PAI-Pulse.vbs'

# Resolve powershell.exe absolutely so the login launch does not depend on PATH.
$psExe = Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe'
if (-not (Test-Path $psExe)) { $psExe = 'powershell.exe' }

# VBScript string-escape: double every embedded double-quote.
$psExeEsc  = $psExe.Replace('"', '""')
$hiddenEsc = $hiddenPs1.Replace('"', '""')

$vbs = @"
' PAI Pulse - per-user Startup launcher (auto-generated by install-pulse-autostart.ps1).
' Launches start-pulse-hidden.ps1 with no visible console window at every login.
Dim shell
Set shell = CreateObject("WScript.Shell")
shell.Run "$psExeEsc -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ""$hiddenEsc""", 0, False
"@

Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII
Write-Host "  ok Registered autostart: $vbsPath"

# Probe :31337 with a raw HttpWebRequest, Proxy explicitly disabled. We do NOT
# use Invoke-WebRequest here: in Windows PowerShell 5.1 it does WPAD proxy
# auto-discovery and progress rendering that add ~2s per call even for
# localhost, which both slows the loop and can exceed the caller's timeout.
# HttpWebRequest with Proxy=$null is the fast, curl-equivalent path (~30ms).
function Test-PulseUp {
    try {
        $req = [System.Net.HttpWebRequest]::Create('http://127.0.0.1:31337/notify')
        $req.Method = 'POST'; $req.ContentType = 'application/json'
        $req.Proxy = $null; $req.Timeout = 2000
        $bytes = [System.Text.Encoding]::ASCII.GetBytes('{"message":"","voice_enabled":false}')
        $s = $req.GetRequestStream(); $s.Write($bytes, 0, $bytes.Length); $s.Close()
        $resp = $req.GetResponse()
        $code = [int]$resp.StatusCode; $resp.Close()
        return ($code -ge 200 -and $code -lt 500)
    } catch [System.Net.WebException] {
        # A 4xx still proves Pulse owns the route. Any other WebException
        # (refused / timeout) means not up yet.
        $r = $_.Exception.Response
        if ($r) { $c = [int]$r.StatusCode; return ($c -ge 200 -and $c -lt 500) }
        return $false
    } catch {
        return $false
    }
}

# 2. Start Pulse now (idempotent - the launcher skips if :31337 is up).
& $psExe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File $hiddenPs1

# 3. Health-check :31337, mirroring manage.sh (wait up to 10s for bind).
for ($i = 0; $i -lt 20; $i++) {
    Start-Sleep -Milliseconds 500
    if (Test-PulseUp) {
        Write-Host "  ok Pulse running on :31337 (voice + dashboard + observability)."
        exit 0
    }
}

Write-Error "Pulse autostart registered but :31337 did not bind within 10s. Check $pulseDir\pulse-server.log.err"
exit 1
